version: '3.8'

services:

  app:
    container_name: prodApp
    restart: always
    build:
      context: ../../.
      dockerfile: deploy/docker/app/Dockerfile
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:${APP_PORT}"]
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - "db_volume:/usr/app/data:rw"
      - "static_volume:/usr/app/staticfiles"
    expose:
      - "${APP_PORT}"
    environment:
      - DEBUG=${APP_DEBUG}
      - SECRET_KEY=${APP_SECRET_KEY}
      - ALLOWED_HOSTS=${APP_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${APP_CSRF_TRUSTED_ORIGINS}

      - DB_NAME=${DB_NAME}

  nginx:
    container_name: prodNginx
    restart: always
    build:
      context: ../../.
      dockerfile: deploy/docker/nginx/Dockerfile
    volumes:
      - static_volume:/home/app/config/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=80
      - APP_HOST=app
      - APP_PORT=${APP_PORT}

volumes:
  db_volume:
  static_volume:
